### ISSUE TITLE
submodule error when using "module procedure functionName"

### ISSUE THREAD

**Issue by leonfoks** [cmacmackin/ford#199]
I have two files inserted below that are causing me the issues.  They contain a simple example where the function in an interface defined in a parent module is implemented in a submodule using the "module procedure functionName" approach. 

Im using Ford 5.0.6, and the code compiles with gfortran 6.3.0

I get the following error:
Traceback (most recent call last):
  File "d:\anaconda27\envs\py35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda27\envs\py35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda27\envs\py35\Scripts\ford.exe\__main__.py", line 9, in <module>
  File "d:\anaconda27\envs\py35\lib\site-packages\ford\__init__.py", line 357, in run
    main(proj_data,proj_docs,md)
  File "d:\anaconda27\envs\py35\lib\site-packages\ford\__init__.py", line 320, in main
    project.correlate()
  File "d:\anaconda27\envs\py35\lib\site-packages\ford\fortran_project.py", line 232, in correlate
    for function in module.modfunctions:
AttributeError: 'FortranSubmodule' object has no attribute 'modfunctions'

In fortran_project.py:
If I put the function in module.modfunctions: in a try: except: I also get the following error
    for subroutine in module.modsubroutines:
AttributeError: 'FortranSubmodule' object has no attribute 'modsubroutines'

If I put both in a try: except: Ford completes.  The documentation contains an entry for the submodule but does not contain easy links to the submodule.  To get there, I have to got to the source file which states the submodule category on the left. 

Perhaps it fails because the "module procedure functionName" has no declarations of incoming variables, nor an explicit module function / module subroutine specified, since they are already defined in the parent module interface?

Thanks for your time!

File: aModule.f90
module aModule
implicit none
private
public :: anInterface
interface anInterface
  module function anInterface_r(this) result(yes)
    real :: this
    logical :: yes
  end function
  module function anInterface_d(this) result(yes)
    real*8 :: this
    logical :: yes
  end function
end interface
end module

File: aSubModule.f90
submodule (aModule) aSubModule
implicit none
contains
module procedure anInterface_r
yes = .true.
end procedure
end submodule

**Comment by cmacmackin** [comment]
Thanks for the bug report. I can confirm the error. It's odd, since FORD is working properly on a very similar bit of code in some software of mine. When I find time to do some work on ford (hopefully in a few weeks) I'll figure out what the issue is.

**Comment by leonfoks** [comment]
Thanks for getting back to me, very strange. If there is anything I can do, just let me know.

On a side note, I have been having submodule issues with SConstruct too which is a shame because scons is so nice! CMake works just fine though. I might post a how to on setting up CMake for fortran on multiple operating systems, not sure how useful that might be!

**Comment by zbeekman** [comment]
@leonfoks I would enjoy such a post. Are you on twitter, and do you have a blog? I regularly use CMake for Fortran on MacOS and Linux, but always with Make as the generator. Would be curious to see more info esp. for windows builds and using Visual Studio, Xcode, Ninja, etc. (i.e. other generators)

If I recall correctly, submodule support was added to CMake thanks to funding/contract from http://www.sourceryinstitute.org (@sourceryinstitute)

**Comment by cmacmackin** [comment]
I believe I have found the source of the error and it was a really dumb one on my part. FORD was having trouble finding the parent module of your submodules because I was being inconsistent about whether comparisons should be case-insensitive. The next release will include the fix.
